---
title: "Italian Elections"
author: "Mr. Schroeder"
date: "10/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(devtools)
library(tidyr)
library(knitr)
```

```{r, echo=FALSE}
pollofpolls<- read_csv("https://pollofpolls.eu/get/polls/IT-parliament/format/csv")
kable(pollofpolls)

pollofpolls %>% 
  filter(date>="2016-12-04") %>%
  ggplot(aes(x=date)) + geom_line(aes(x=date, y=LN), color = "dark green")

pollofpolls %>% 
  filter(date>="2016-12-04") %>%
  gather(key="party", value =c())

pollofpolls %>% 
  filter(date>="2016-12-04") %>%
  ggplot(aes(x=date)) + 
  geom_line(aes(x=date, y=M5S), color = "yellow") +
  geom_line(aes(x=date, y=PD), color = "pink") +
  geom_line(aes(x=date, y=FdI), color = "dark blue") +
  geom_line(aes(x=date, y=LN), color = "dark green") +
  geom_line(aes(x=date, y=FIPDLFI), color = "blue") +
  geom_line(aes(x=date, y=IdV), color = "dark red")

ggplot(pollofpolls, aes(x=))
pollofpolls %>% 
  filter(date>="2016-12-04") %>%
  arrange(desc(date))
```

